export const COOKIES = {
  AUTH_TOKEN: "AUTH_TOKEN",
} as const;

export const API_KEY = {
  USER: "USER",
  WORKSPACES: "WORKSPACES",
  PROJECTS: "PROJECTS",
  ACTIVE_MEMBERS: "ACTIVE_MEMBERS",
  PROJECTS_MEMBERS: "PROJECTS_MEMBERS",
  PROJECTS_REPORT: "PROJECTS_REPORT",
  WORKSPACES_REPORT: "WORKSPACES_REPORT",
  MEMBERS_REPORT: "MEMBERS_REPORT",
  SUMMARY_REPORT: "SUMMARY_REPORT",
};
