export const COOKIES = {
  AUTH_TOKEN: "AUTH_TOKEN",
} as const;

export const API_KEY = {
  USER: "USER",
  WORKSPACES: "WORKSPACES",
  PROJECTS: "PROJECTS",
  PROJECTS_REPORT: "PROJECTS_REPORT",
};
