<template>
  <v-list
    density="compact"
    nav
  >
    <v-list-item
      prepend-icon="mdi-home-city"
      title="Home"
      value="home"
    ></v-list-item>
    <v-list-item
      prepend-icon="mdi-clock-fast"
      title="Time tracker"
      value="account"
    ></v-list-item>
    <v-list-item
      prepend-icon="mdi-file"
      title="My Projects"
      value="account"
    ></v-list-item>
    <v-list-item
      prepend-icon="mdi-chart-bar"
      title="Reports"
      value="users"
    ></v-list-item>
    <v-list-item
      prepend-icon="mdi-account-group-outline"
      title="Team"
      value="users"
    ></v-list-item>
  </v-list>
</template>
